package org.entando.plugins.survey.dto.question;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import org.entando.plugins.survey.dto.answer.AnswerDto;
import org.entando.plugins.survey.model.Answer;
import org.entando.plugins.survey.model.Question;
import org.entando.plugins.survey.model.answer.AnswerList;
import org.entando.plugins.survey.model.question.QuestionList;
import org.entando.plugins.survey.model.question.QuestionText;

import java.util.List;
import java.util.UUID;

@Data
@EqualsAndHashCode(callSuper = true)
public class QuestionListDto extends QuestionDto {
    List<QuestionList.Option> options;

    @JsonProperty("multiple_choice")
    boolean multipleChoice;

    @Builder
    public QuestionListDto(String id, String question, List<QuestionList.Option> options, boolean multipleChoice) {
        super(id, Question.QuestionType.list, question);

        this.options = options;
        this.multipleChoice = multipleChoice;
    }

    @Override
    public Question toModel() {
        return QuestionList.builder()
                .id(UUID.randomUUID()) //TODO should be generated by DB?
                .question(question)
                .multipleChoice(multipleChoice)
                .options(options)
                .build();
    }
}
