package org.entando.plugins.survey.dto.question;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import org.entando.plugins.survey.dto.answer.AnswerDto;
import org.entando.plugins.survey.model.Answer;
import org.entando.plugins.survey.model.Question;
import org.entando.plugins.survey.model.answer.AnswerRate;
import org.entando.plugins.survey.model.question.QuestionList;
import org.entando.plugins.survey.model.question.QuestionRate;
import org.entando.plugins.survey.model.question.QuestionText;

import java.util.UUID;

@Data
@EqualsAndHashCode(callSuper = true)
public class QuestionRateDto extends QuestionDto {
    @JsonProperty("min_rate")
    int minRate;

    @JsonProperty("max_rate")
    int maxRate;

    @Builder
    public QuestionRateDto(String id, String question, int order, int minRate, int maxRate) {
        super(id, question, order);

        this.minRate = minRate;
        this.maxRate = maxRate;
    }


    @Override
    public Question toModel() {
        return QuestionRate.builder()
                .id(UUID.randomUUID()) //TODO should be generated by DB?
                .order(order)
                .question(question)
                .minRate(minRate)
                .maxRate(maxRate)
                .build();
    }
}
