package org.entando.plugins.survey.dto.question;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import org.entando.plugins.survey.dto.answer.AnswerDto;
import org.entando.plugins.survey.model.Answer;
import org.entando.plugins.survey.model.Question;
import org.entando.plugins.survey.model.answer.AnswerText;
import org.entando.plugins.survey.model.question.QuestionList;
import org.entando.plugins.survey.model.question.QuestionText;

import java.util.UUID;

@Data
@EqualsAndHashCode(callSuper = true)
public class QuestionTextDto extends QuestionDto {
    @JsonProperty("min_length")
    int minLength;

    @JsonProperty("max_length")
    int maxLength;

    @Builder
    public QuestionTextDto(String id, String question, int order, int minLength, int maxLength) {
        super(id, question, order);

        this.minLength = minLength;
        this.maxLength = maxLength;
    }


    @Override
    public Question toModel() {
        return QuestionText.builder()
                .id(UUID.randomUUID()) //TODO should be generated by DB?
                .order(order)
                .question(question)
                .minLength(minLength)
                .maxLength(maxLength)
                .build();
    }
}
