package org.entando.plugins.survey.dto.answer;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import org.entando.plugins.survey.model.Answer;
import org.entando.plugins.survey.model.Question;
import org.entando.plugins.survey.model.answer.AnswerList;
import org.entando.plugins.survey.model.answer.AnswerRate;
import org.entando.plugins.survey.model.answer.AnswerText;
import org.entando.plugins.survey.model.question.QuestionList;

import java.util.List;
import java.util.UUID;

@Data
@EqualsAndHashCode(callSuper = true)
public class AnswerTextDto extends AnswerDto {
    @JsonProperty("answer_text")
    String answerText;

    @Builder
    public AnswerTextDto(String questionId, String answerText) {
        super(questionId, Question.QuestionType.list);

        this.answerText = answerText;
    }


    @Override
    public Answer toModel() {
        return AnswerText.builder()
                .id(UUID.randomUUID()) //TODO should be generated by DB?
                .question(QuestionList.builder()
                        .id(UUID.fromString(questionId))
                        .build())
                .answerText(answerText)
                .build();
    }
}
