package org.entando.plugins.survey.dto.answer;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import org.entando.plugins.survey.model.Answer;
import org.entando.plugins.survey.model.Question;
import org.entando.plugins.survey.model.answer.AnswerRate;
import org.entando.plugins.survey.model.question.QuestionList;

import java.util.UUID;

@Data
@EqualsAndHashCode(callSuper = true)
public class AnswerRateDto extends AnswerDto {
    @JsonProperty("selected_rate")
    int selectedRate;

    @Builder
    public AnswerRateDto(String questionId, int selectedRate) {
        super(questionId, Question.QuestionType.rate);

        this.selectedRate = selectedRate;
    }


    @Override
    public Answer toModel() {
        return AnswerRate.builder()
                .id(UUID.randomUUID()) //TODO should be generated by DB?
                .question(QuestionList.builder()
                        .id(UUID.fromString(questionId))
                        .build())
                .selectedRate(selectedRate)
                .build();
    }
}
