package org.entando.plugins.survey.dto.answer;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import org.entando.plugins.survey.model.Answer;
import org.entando.plugins.survey.model.Question;
import org.entando.plugins.survey.model.answer.AnswerList;
import org.entando.plugins.survey.model.question.QuestionList;

import java.util.List;
import java.util.UUID;

@Data
@EqualsAndHashCode(callSuper = true)
public class AnswerListDto extends AnswerDto {
    @JsonProperty("selected_keys")
    List<String> selectedOptionsKeys;

    @Builder
    public AnswerListDto(String questionId, List<String> selectedOptionsKeys) {
        super(questionId, Question.QuestionType.list);

        this.selectedOptionsKeys = selectedOptionsKeys;
    }

    @Override
    public Answer toModel() {
        return AnswerList.builder()
                .id(UUID.randomUUID()) //TODO should be generated by DB?
                .question(QuestionList.builder()
                        .id(UUID.fromString(questionId))
                        .build())
                .selectedKeys(selectedOptionsKeys)
                .build();
    }
}
